# Generated by Django 2.2.7 on 2019-12-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discount',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('DRESSES', 'Dresses'), ('SWEATERS', 'Sweaters'), ('JACKETS', 'Jackets'), ('BLOUSES', 'Blouses'), ('SHOES', 'Shoes'), ('SKIRTS', 'Skirts'), ('BOTTOMS', 'Bottoms')], max_length=3),
        ),
    ]
