# Generated by Django 2.2.7 on 2019-12-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191214_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('DRESSES', 'Dresses'), ('SWEATERS', 'Sweaters'), ('JACKETS', 'Jackets'), ('BLOUSES', 'Blouses'), ('SHOES', 'Shoes'), ('SKIRTS', 'Skirts'), ('BOTTOMS', 'Bottoms')], max_length=8),
        ),
    ]
