# Generated by Django 2.2.7 on 2019-12-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20191216_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ship_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
