# Generated by Django 2.2.7 on 2019-12-17 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20191216_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
